### ISSUE TITLE
Default 2d input handlers may not all be disabled at 4.4

### ISSUE THREAD

**Issue by wmlrose** [kingy68/esri-javascript-draw-4#8]
First, thanks for this tool. It works great in my 4.3 application!

However, upgrading to jsapi 4.4 appears to prevent the module from disabling all esri.views.2d.input.handlers.

**Comment by wmlrose** [comment]
Looks like this is at least partially resolved by referencing view.inputManager.viewEvents.inputManager._handlers for 2d instead of view.inputManager._handlers (just like 3d).

**Comment by kingy68** [comment]
Hey, yeah the handlers seem to have changed at every version so far. When I get a chance in the next day or two, I'll try to update.

**Comment by kingy68** [comment]
Have now updated for the 4.4 API. Going to mark this as resolved.
